---
name: docker

on:
  pull_request:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'true'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      -
        name: meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ secrets.HARBOR_URL }}/stratumfarm/phantomias
          tags: |
            type=raw,event=tag,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=semver,event=tag,pattern={{version}}
            type=semver,event=tag,pattern={{major}}.{{minor}}
            type=ref,event=pr
      -
        name: Build and push phantomias
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - 
        name: image digest
        run: echo ${{ steps.docker_build.outputs.digest }}