---
name: goreleaser

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
    - 
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'true'
    - 
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    -
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - 
      uses: docker/setup-qemu-action@v2
    - 
      uses: docker/setup-buildx-action@v2
    -  
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        args: release --rm-dist
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}